project_id = "qfwlyvkumdplegppeqwx"

[functions.whatsapp-webhook]
verify_jwt = false

[functions.n8n-whatsapp-webhook]
verify_jwt = false

[functions.mega-webhook]
verify_jwt = false

[functions.lead-capture]
verify_jwt = false
